name = "bigratmonster"
author = "AmeMeida"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24bfcd90272d0945252d403ac7d91829be3994fd0279bfe7f7514983156767cc"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
