name = "bigratmonster"
author = "AmeMeida"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de01b5423273734c85dbcfa9d5e97b8b879340aa9ac40d98b28a12209e5cf77d"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
