name = "bigratmonster"
author = "AmeMeida"
version = "4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94ccdb67e21ad3cc8b49b72299c6d9912f93e0484da52465f9ccdefeabab4101"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
