name = "bigratmonster"
author = "AmeMeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25f8be91e927b353f9eae277402688f07b2072afd1a8611e57400b667ae17cf0"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
