name = "bigratmonster"
author = "AmeMeida"
version = "4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b8d7eef5c040929406f7ea9e9ec6b762b5e8b17800cef811cb37b584f66ad6c"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
