name = "bigratmonster"
author = "AmeMeida"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "692fbd0041e317eb91ea64d8409764156b44dd1d024ad75faad79914c2aa925f"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
