name = "bigratmonster"
author = "AmeMeida"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69ebb828a5e34fe5e815240a29120fc469cf77515e877b18709494c98107f186"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
