name = "bigratmonster"
author = "AmeMeida"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aa110d6f2be4d8ced4145eeace18e838301fd3aad172a778467957d94941bff"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
