name = "bigratmonster"
author = "AmeMeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66a913f30046c2624a595f467e083718df8580fbe00b73a6b284eca686ab7315"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
