name = "bigratmonster"
author = "AmeMeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c1424d35a6cf1a9ecdb0e5afae1f09af8f6daca4a03c161bf8b96653f722f55"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
