name = "bigratmonster"
author = "AmeMeida"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "951f405632f1ee0792a72636cc0f8621c7474e94bf428f24af20f66b9a61601d"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
