name = "bigratmonster"
author = "AmeMeida"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce59bcb00d97e3e1627bd16f4c10261eeddcb8ed67ad21c962052cf64ade380"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
