name = "bigratmonster"
author = "AmeMeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c485d34aa04c286b8ab2a388d82db4d2d9b06b1e07cf32ccd28fc01504a3679"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
