name = "bigratmonster"
author = "AmeMeida"
version = "4.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9130de1b9f68a1cd35cb5d76b3fff215796b9f09fbe253241901cf8715911c3"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
