name = "bigratmonster"
author = "AmeMeida"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a07805ad278f8b13bc451212bf9ed291d4a6398a417bab77cb44dffa0c658329"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/resources"
